spring.application.name=financebackend

jwt.secret=KoFG421dyf8fJ6/EDEdFvywL9dIlQ/v/6h+FZa+kp0Y=
# 1 hour in milliseconds
jwt.expiration=3600000   

# Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Custom Port
server.port=9092